### PR TITLE
Fix misaligned pointer handling

### LINKED ISSUE #72: C++ library does casts with potentially undefined behaviour
Several functions perform casts of the kind
```
const uint64_t *ptr2 = reinterpret_cast<const uint64_t *>(ptr1);
```
(they were adapted from C-style casts, which basically mean the same thing as `reinterpret_cast`). Such a cast is only valid if `ptr1` is aligned to an 8-byte boundary, which it (clearly) normally is, however this is not guaranteed in any sense. See [here](https://wiki.sei.cmu.edu/confluence/display/c/EXP36-C.+Do+not+cast+pointers+into+more+strictly+aligned+pointer+types) for some extra info.

The fix should be to require 8-byte aligned input, since we do use that assumption to speed up loading array elements into memory.

### PR DESCRIPTION
**Pull request by mhsiah**
This PR fixes #72. It introduces a new function, `adjust_ptr_alignment()`, which will return the pointer it's given if that pointer is already aligned, otherwise it will copy the whole array somewhere that is properly aligned. Obviously the latter case is way way slower, but at least it doesn't segfault anymore.

### CODE REVIEW

File: _cffi_build/dice_one_against_many.cpp [hunk 1]
```diff
@@ -315,9 +377,11 @@ extern "C"
             const char *arrays, int narrays, int array_bytes) {
         // assumes WORD_BYTES divides array_bytes
         int nwords = array_bytes / WORD_BYTES;
-        const uint64_t *u = reinterpret_cast<const uint64_t *>(arrays);
+        // The static_cast is to avoid int overflow in the multiplication
+        size_t total_bytes = static_cast<size_t>(narrays) * array_bytes;
+        auto ptr = adjust_ptr_alignment(arrays, total_bytes);
+        auto u = ptr.get();
```
Comment (sjhardy) [inline _cffi_build/dice_one_against_many.cpp]: Is u really such a complicated type it needs to be auto? (It just feels less understandable to my old school C++ prejudices).

File: tests/test_util.py [hunk 2]
```diff
@@ -31,3 +32,55 @@ def test_popcount_vector(L):
...
+    # arrays offsets forward by offset bytes.
+    misaligned_addr = int(ffi.cast('uintptr_t', many)) + offset
+    misaligned_many = ffi.cast('char *', misaligned_addr)
+    lib.popcount_arrays(c_popcounts, misaligned_many, n - 1, arr_bytes)
+
+    # restrict to the offset bytes
+    bas_as_bytes = bas_as_bytes[offset : (n-1)*arr_bytes + offset]
+    # split into chunks corresponding to clks
+    chunks = [c for c in util.chunks(bas_as_bytes, arr_bytes)]
+    # Can Hamish count?
```
Comment (sjhardy) [inline tests/test_util.py]: Yes he can!
